name: Continuous Integration

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
      - release/*
concurrency:
  group: marketplace-contracts-build-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build & Test
    timeout-minutes: 20
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: 'npm'
          cache-dependency-path: package-lock.json
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci --no-audit
      - name: Run lint
        run: npm run lint
      - name: Run test
        run: npm run test

