name: Continuous Integration

on:
  pull_request:
    branches:
      - master
      - release/*
  push:
    branches:
      - master
      - release/*

jobs:
  build:
    name: Build
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 16.1.0
        os:
          - ubuntu-16.04
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Node ${{ matrix.node_version }} - x64 on ${{ matrix.os }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install Npm 6.0.1
        run: npm i -g npm@6.0.1
      - uses: actions/cache@v2.1.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: |
          npm ci
      - name: Run lint and test
        run: |
          npm run lint
          npm run test

